// Product data sourced from the aims-commerce PostgreSQL backend (Supabase).
// Image URLs are loaded from Supabase Storage; the rest of the shape mirrors the
// legacy onrender API so the existing redux actions, filters, and detail screen
// keep working without changes.
// Source query: GET /rest/v1/products?select=id,name,image,category,brand,price,description,rating,num_reviews

const data = { products: [
  {
    _id: 1,
    name: "Acer Nitro 5",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p7.jpg",
    category: "Electronics",
    price: 875.05,
    countInStock: 10,
    brand: "Acer",
    rating: 0.0,
    numReviews: 0,
    description: "Acer Nitro 5 Gaming Laptop, 9th Gen Intel Core i5-9300H, NVIDIA GeForce GTX 1650, 15.6",
  },
  {
    _id: 2,
    name: "Acer Predator Helios",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p4.jpg",
    category: "Electronics",
    price: 1325.29,
    countInStock: 10,
    brand: "Acer",
    rating: 0.0,
    numReviews: 0,
    description: "Acer Predator Helios 300 Gaming Laptop, Intel i7-10750H, NVIDIA GeForce RTX 2060 6GB",
  },
  {
    _id: 3,
    name: "Adidas Premium Pants",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p15.jpg",
    category: "Pants",
    price: 150.0,
    countInStock: 10,
    brand: "Under Armour",
    rating: 0.0,
    numReviews: 0,
    description: "Adidas Premium Slack Pants ",
  },
  {
    _id: 4,
    name: "Adidas Stripe Shirt",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p12.jpg",
    category: "Shirts",
    price: 140.0,
    countInStock: 10,
    brand: "Adidas",
    rating: 0.0,
    numReviews: 0,
    description: "Adidas Stripe Polo shirt",
  },
  {
    _id: 5,
    name: "ASUS ROG Strix Scar 15 (2020)",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p3.jpg",
    category: "Electronics",
    price: 799.59,
    countInStock: 10,
    brand: "Asus",
    rating: 0.0,
    numReviews: 0,
    description: "ASUS ROG Strix Scar 15 (2020) Gaming Laptop, 15.6” 240Hz IPS Type FHD, NVIDIA GeForce RTX 2070 Super, Intel Core i7-10875H, 16GB DDR4, 1TB PCIe NVMe SSD, Per-Key RGB KB, Windows 10, G532LWS-DS76",
  },
  {
    _id: 6,
    name: "ASUS TUF Gaming 27inch 2K HDR Gaming Monitor",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p6.jpg",
    category: "Electronics",
    price: 659.46,
    countInStock: 10,
    brand: "Asus",
    rating: 0.0,
    numReviews: 0,
    description: "ASUS TUF Gaming 27inch 2K HDR Gaming Monitor (VG27AQ) - WQHD (2560 x 1440), 165Hz (Supports 144Hz), 1ms, Extreme Low Motion Blur",
  },
  {
    _id: 7,
    name: "ASUS UX534FTC",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p2.jpg",
    category: "Electronics",
    price: 1299.09,
    countInStock: 10,
    brand: "Asus",
    rating: 3.5,
    numReviews: 2,
    description: "ASUS UX534FTC-AS77 ZenBook 15 Laptop, 15.6” UHD 4K NanoEdge Display, Intel Core i7-10510U, GeForce GTX 1650, 16GB, 512GB PCIe SSD, ScreenPad 2.0, Amazon Alexa Compatible, Windows 10, Icicle Silver",
  },
  {
    _id: 8,
    name: "Asus ZenBook Pro Duo",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p1.jpg",
    category: "Electronics",
    price: 899.49,
    countInStock: 10,
    brand: "Asus",
    rating: 0.0,
    numReviews: 0,
    description: "Asus ZenBook Pro Duo UX581 15.6inch 4K UHD NanoEdge Bezel Touch, Intel Core i9-9980HK, 32GB RAM, 1TB PCIe SSD, GeForce RTX 2060",
  },
  {
    _id: 9,
    name: "Cody Frost",
    image: "https://picsum.photos/seed/cody-frost/800/600",
    category: "Electronics",
    price: 405.0,
    countInStock: 10,
    brand: "Proident aut exerci",
    rating: 0.0,
    numReviews: 0,
    description: "Ullam sed eius aperi",
  },
  {
    _id: 10,
    name: "GE Forcce RTX 2080",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p8.jpg",
    category: "Gaming",
    price: 1249.05,
    countInStock: 10,
    brand: "Nvidia",
    rating: 0.0,
    numReviews: 0,
    description: "GeForce RTXTM graphics cards are powered by the Turing GPU architecture and the all-new RTX platform. This gives you up to 6X the performance of previous-generation graphics cards and brings the power of real-time ray tracing and AI to games",
  },
  {
    _id: 11,
    name: "HP Pavilion Gaming",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p5.jpg",
    category: "Electronics",
    price: 799.25,
    countInStock: 10,
    brand: "HP",
    rating: 0.0,
    numReviews: 0,
    description: "HP Pavilion Gaming 15-Inch Micro-EDGE Laptop, Intel Core i5-9300H Processor, NVIDIA GeForce GTX 1650 4GB",
  },
  {
    _id: 12,
    name: "Magee Day",
    image: "https://picsum.photos/seed/magee-day/400/300",
    category: "Autem mollit sit exp",
    price: 502.0,
    countInStock: 10,
    brand: "Incidunt doloribus ",
    rating: 0.0,
    numReviews: 0,
    description: "Tempora sint exercit",
  },
  {
    _id: 13,
    name: "Nike Polo Shirt",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p10.jpg",
    category: "Shirts",
    price: 100.0,
    countInStock: 10,
    brand: "Nike",
    rating: 0.0,
    numReviews: 0,
    description: "Nike White Polo shirt",
  },
  {
    _id: 14,
    name: "Nike Slack pants",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p13.jpg",
    category: "Pants",
    price: 125.0,
    countInStock: 10,
    brand: "Nike",
    rating: 0.0,
    numReviews: 0,
    description: "Formal Slack Pants ",
  },
  {
    _id: 15,
    name: "Razer FHD 144hz",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p9.jpg",
    category: "Gaming",
    price: 1249.05,
    countInStock: 10,
    brand: "Nvidia",
    rating: 0.0,
    numReviews: 0,
    description: "Just when you thought a gaming laptop couldn’t be any more beastly—introducing the new Razer Blade 15, now available with the latest 12th Gen Intel® Core™ processor (14-core) and NVIDIA® GeForce RTX™ 30 Series Laptop GPUs for the most powerful gaming laptop graphics ever. With your choice of a Full HD 360Hz, QHD 240Hz (G-SYNC), or new UHD 144Hz display, enjoy unrivalled performance packed into the thinnest 15” RTX gaming laptop chassis ever.",
  },
  {
    _id: 16,
    name: "Under Armour Formal pants",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p14.jpg",
    category: "Pants",
    price: 155.0,
    countInStock: 10,
    brand: "Under Armour",
    rating: 0.0,
    numReviews: 0,
    description: "Premium Slack Pants ",
  },
  {
    _id: 17,
    name: "Under Armour Shirt",
    image: "https://tmnsezftbqitxibndtlk.supabase.co/storage/v1/object/public/uploads/p11.jpg",
    category: "Shirts",
    price: 120.0,
    countInStock: 10,
    brand: "Under Armour",
    rating: 0.0,
    numReviews: 0,
    description: "Under Armour Polo",
  }
] };

export default data;
